version: "3"

tasks:
  typescript-action-run-local-action:
    desc: Run the typescript action with @github/local-action
    dir: ../../06-authoring-actions/javascript-actions/typescript-action-with-build-mine
    cmds:
      - npm run local-action

  typescript-action-test:
    desc: Run the typescript action with @github/local-action
    dir: ../../06-authoring-actions/javascript-actions/typescript-action-with-build-mine
    cmds:
      - npm run test
